;; ---------------------------------------------------
;;|                    CONDITIONS                     |
;; ---------------------------------------------------
(defun compile-if (exp env fenv namef)
  (let 
		(
			(else (gensym "else"))
			(endIf (gensym "endIf"))
		)
    (append (compiler (car exp) env fenv namef)  
	    '((CMP :R0 (:DIESE nil)))
	    `((JEQ (@ ,else)))
	    (compiler (cadr exp) env fenv namef) 
	    `((JMP (@ ,endIf)))
	    `((@ ,else))  
	    (compiler (caddr exp) env fenv namef)
	    `((@ ,endIf))
		)
	)
)

(defun compile-cond (exp endLabel env fenv namef)
  (if (null exp)
    (append '((MOVE (:DIESE NIL) :R0)) `((@ , endLabel)))   
    (let ((labelcond (gensym "labelcond")))                              
      (append (compiler (caar exp) env fenv namef)                
	      '((CMP :R0 (:DIESE NIL)))                                
	      `((JEQ (@ ,labelcond)))                             
	      (compiler (cadar exp) env fenv namef)              
	      `((JMP (@ ,endLabel)))                               
	      `((@ ,labelcond))                                    
	      (compile-cond (cdr exp) endLabel env fenv namef)
			)
		)
	)
)