INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(4 ,0 ,3,"Gilbert","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(3,1,2,"pseudo","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(6 ,2 ,5,"@Gilbertlebg","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(5,3,2,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(8 ,4 ,7,"Bonjour, je m'appelle Gilbert","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(7,5,2,"description","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(9,6,2,"picture","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(11,7,10,"follower","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(10,8,2,"followers","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(13,9,12,"follow","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(14,10,12,"follow","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(12,11,2,"follows","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(2,12,1,"profile","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(17 ,13 ,16,"Michel","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(16,14,15,"pseudo","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(19 ,15 ,18,"@Micheloupastaga","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(18,16,15,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(21 ,17 ,20,"Bonjour, je m'appelle Michel, c'est cool nan ?","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(20,18,15,"description","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(22,19,15,"picture","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(23,20,15,"followers","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(25,21,24,"follow","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(24,22,15,"follows","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(15,23,1,"profile","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(28 ,24 ,27,"Rick","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(27,25,26,"pseudo","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(30 ,26 ,29,"@Astley","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(29,27,26,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(32 ,28 ,31,"NEVER GONNA GIVE U UP ! NEVER GONNA LET U DOWN !","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(31,29,26,"description","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(33,30,26,"picture","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(35,31,34,"follower","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(34,32,26,"followers","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(37,33,36,"follow","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(36,34,26,"follows","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(26,35,1,"profile","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(1,36,0,"profiles","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(42 ,37 ,41,"1600412469","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(41,38,40,"timestamp","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(44 ,39 ,43,"UTC+1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(43,40,40,"fuseau","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(40,41,39,"date","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(47 ,42 ,46,"43.610658","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(46,43,45,"longitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(49 ,44 ,48,"3.876479","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(48,45,45,"latitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(51 ,46 ,50,"Montpellier","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(50,47,45,"city","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(53 ,48 ,52,"France","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(52,49,45,"country","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(45,50,39,"location","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(56 ,51 ,55,"@Micheloupastaga","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(55,52,54,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(58 ,53 ,57,"#love","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(57,54,54,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(60 ,55 ,59,"@Astley","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(59,56,54,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(54,57,39,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(62 ,58 ,61,"3","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(61,59,39,"nbrRt","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(63,60,39,"responses","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(39,61,38,"tweet","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(67 ,62 ,66,"1602326032","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(66,63,65,"timestamp","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(69 ,64 ,68,"UTC+1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(68,65,65,"fuseau","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(65,66,64,"date","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(72 ,67 ,71,"43.610658","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(71,68,70,"longitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(74 ,69 ,73,"3.876479","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(73,70,70,"latitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(76 ,71 ,75,"Montpellier","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(75,72,70,"city","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(78 ,73 ,77,"France","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(77,74,70,"country","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(70,75,64,"location","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(81 ,76 ,80,"I love u too","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(80,77,79,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(83 ,78 ,82,"@Gilbertlebg","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(82,79,79,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(85 ,80 ,84,"#love","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(84,81,79,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(87 ,82 ,86,"#friend","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(86,83,79,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(79,84,64,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(89 ,85 ,88,"1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(88,86,64,"nbrRt","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(90,87,64,"responses","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(64,88,38,"tweet","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(94 ,89 ,93,"1602324015","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(93,90,92,"timestamp","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(96 ,91 ,95,"UTC+1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(95,92,92,"fuseau","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(92,93,91,"date","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(99 ,94 ,98,"43.610658","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(98,95,97,"longitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(101 ,96 ,100,"3.876479","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(100,97,97,"latitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(103 ,98 ,102,"Montpellier","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(102,99,97,"city","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(105 ,100 ,104,"France","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(104,101,97,"country","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(97,102,91,"location","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(108 ,103 ,107,"I LOVE CALLOFDUTY, come play with my friends","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(107,104,106,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(110 ,105 ,109,"@Astley","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(109,106,106,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(112 ,107 ,111,"@Gilbertlebg","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(111,108,106,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(114 ,109 ,113,"#gaming","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(113,110,106,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(116 ,111 ,115,"#callofduty","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(115,112,106,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(118 ,113 ,117,"#frenchmonster","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(117,114,106,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(106,115,91,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(120 ,116 ,119,"2","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(119,117,91,"nbrRt","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(125 ,118 ,124,"Me ? You friend ? NO !","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(124,119,123,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(123,120,122,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(122,121,121,"response","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(121,122,91,"responses","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(91,123,38,"tweet","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(129 ,124 ,128,"564019200","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(128,125,127,"timestamp","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(131 ,126 ,130,"UTC+1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(130,127,127,"fuseau","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(127,128,126,"date","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(134 ,129 ,133,"26","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(133,130,132,"longitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(136 ,131 ,135,"48","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(135,132,132,"latitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(138 ,133 ,137,"New York","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(137,134,132,"city","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(140 ,135 ,139,"Etats-Unis","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(139,136,132,"country","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(132,137,126,"location","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(143 ,138 ,142,"#I","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(144 ,139 ,142,"<","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(145 ,140 ,142,"3XML","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(142,141,141,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(147 ,142 ,146,"@GilbertLeBG","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(146,143,141,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(149 ,144 ,148,"Never gonna give you up Never gonna let you down","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(150 ,145 ,148,"Never gonna run around and desert you Never gonna make you cry","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(151 ,146 ,148,"Never gonna say goodbye Never gonna tell a lie and hurt you","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(148,147,141,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(153 ,148 ,152,"#rickrolled","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(152,149,141,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(141,150,126,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(155 ,151 ,154,"776970984","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(154,152,126,"nbrRt","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(160 ,153 ,159,"Рик Ролд Бро !","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(159,154,158,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(158,155,157,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(157,156,156,"response","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(164 ,157 ,163,"Hola me llamo Toma","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(163,158,162,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(162,159,161,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(161,160,156,"response","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(168 ,161 ,167,"noob","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(167,162,166,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(166,163,165,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(165,164,156,"response","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(156,165,126,"responses","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(126,166,38,"tweet","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(172 ,167 ,171,"1609484400","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(171,168,170,"timestamp","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(174 ,169 ,173,"UTC+1","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(173,170,170,"fuseau","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(170,171,169,"date","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(177 ,172 ,176,"43.610658","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(176,173,175,"longitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(179 ,174 ,178,"3.876479","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(178,175,175,"latitude","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(181 ,176 ,180,"Montpellier","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(180,177,175,"city","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(183 ,178 ,182,"France","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(182,179,175,"country","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(175,180,169,"location","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(186 ,181 ,185,"Bonne année !","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(185,182,184,"text","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(188 ,183 ,187,"@GilbertLeBG","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(187,184,184,"ref-user","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(190 ,185 ,189,"#bonneresolution","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(189,186,184,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(192 ,187 ,191,"#nouvelleannee","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(191,188,184,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(194 ,189 ,193,"#tagsuperoriginal","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(193,190,184,"hashtag","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(184,191,169,"corps","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(196 ,192 ,195,"0","txt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(195,193,169,"nbrRt","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(197,194,169,"responses","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(169,195,38,"tweet","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(38,196,0,"tweets","elt");
INSERT INTO NODE(begin,end,parent,tag,nodtype) VALUES(0,197,0,"twitter","elt");
